### ISSUE TITLE
Redundant `.jl` in new package

### ISSUE THREAD

**Issue by lukem12345** [AlgebraicJulia/AlgebraicTemplate.jl#10]
I created a package named `SEPTransport.jl` from AlgebraicTemplate.

I followed the steps in the readme:
```repl
 1060  git clone git@github.com:AlgebraicJulia/SEPTransport.jl
 1061  cd SEPTransport.jl/
 1062  ls
 1063  cat init.sh 
 1064  ./init.sh SEPTransport.jl
 1065  history 
```

The title in the README became `SEPTransport.jl.jl` i.e. It added an extra `.jl`.

<img width="665" alt="image" src="https://github.com/user-attachments/assets/9dd92c51-1655-4772-a413-9e63fe94d4a1">

**Comment by lukem12345** [comment]
Further the main module which should have been named `module SEPTransport` was named `module SEPTransport.jl` in `src/SEPTransport.jl`.

Likewise in `docs/literate/literate_example.jl`, `docs/make.jl`, `docs/src/api.md`, `docs/src/index.md`, `Project.toml`, `docs/Project.toml`.

**Comment by jpfairbanks** [comment]
It looks like this check is trying to make sure that it handles both cases `SEPTransport.jl` and `SEPTransport` with and implied `.jl` suffix. Maybe it makes sense to trim a trailing `.jl` at the top of the script and then the rest of the code can assume that there is no trailing `.jl`

```bash
# rename 
if [[ $REPO == *.jl ]]
then
  mv src/$DEFAULT_REPO.jl src/$REPO
else
  mv src/$DEFAULT_REPO.jl src/$REPO.jl
fi
```

`REPO=$REPO%%.jl` should work

[1] https://stackoverflow.com/questions/125281/how-do-i-remove-the-file-suffix-and-path-portion-from-a-path-string-in-bash

**Comment by quffaro** [comment]
@lukem12345 I fixed the `init.sh` script in [this commit](https://github.com/AlgebraicJulia/AlgebraicTemplate.jl/commit/2bc7f95ff21f002de476fcb1900704bff769dfca) and tested locally.
